enable-module-update = false
parallel-jobs = 1

[YouTube-Morphe]
app-name = "YouTube"

patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"

build-mode = "apk"
arch = "arm64-v8a"
version = "auto"

apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

enable-update-checks = false


[Music-Morphe]
app-name = "Music"

patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"

build-mode = "apk"
arch = "arm64-v8a"
version = "auto"

apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

enable-update-checks = false
