[build]
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"

patches-version = "latest"
cli-version = "latest"

arch = "arm64-v8a"

[YouTube]
package = "com.google.android.youtube"
app-name = "YouTube"

apkmirror-url = "https://www.apkmirror.com/apk/google-inc/youtube"
archive-url = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Music]
package = "com.google.android.apps.youtube.music"
app-name = "Music"

apkmirror-url = "https://www.apkmirror.com/apk/google-inc/youtube-music"
archive-url = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
